# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  vmImageName: ubuntu-latest
  environmentName: 'aspnet-core-devops'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/ASP.NET-Core-Proj*.csproj'
        displayName: 'dotnet restore $(buildConfiguration)'
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/ASP.NET-Core-Proj*.csproj'
          arguments: '--no-restore'
        displayName: 'dotnet build $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          projects: '**/ASP.NET-Core-Proj*.csproj'
          arguments: '--configuration $(buildConfiguration) --no-restore'
        displayName: 'dotnet publish $(buildConfiguration)'
        
      - task: PublishBuildArtifacts@1
        displayName: "Upload Artifacts"
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)/**/*.zip' 
          artifactName: 'aspnet-core-devops'

- stage: Deploy
  displayName: Deploy 
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Azure Web App Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Ansalemo(4388fa06-bf66-4497-82c2-991ba75ecb97)'
          appType: 'webAppLinux'
          WebAppName: 'aspnet-core-devops'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
          RuntimeStack: 'DOTNETCORE|5.0'
