# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  vmImageName: ubuntu-latest
  environmentName: 'aspnet-core-devops'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build Stage
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: .NET 5 SDK
      inputs:
        packageType: 'sdk'
        version: '5.0.100'
        includePreviewVersions: true
    # Replace appSettings.json variables with pipeline environment variables
    - task: replacetokens@3
      displayName: Replace Tokens
      inputs:
        rootDirectory: '$(System.DefaultWorkingDirectory)/'
        targetFiles: '**/appsettings.json'
        encoding: 'auto'
        writeBOM: true
        actionOnMissing: 'warn'
        keepToken: false
        tokenPrefix: '#{'
        tokenSuffix: '}#'
        useLegacyPattern: false
        enableTelemetry: false

    - task: DotNetCoreCLI@2
      displayName: dotnet Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) /p:SourceRevisionId=$(Build.SourceVersion)' 

    - task: DotNetCoreCLI@2
      displayName: dotnet Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifacts
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'drop'
    
          
          