# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  vmImageName: ubuntu-latest
  environmentName: 'aspnet-core-devops'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: UseDotNet@2
        inputs:
          version: '5.0.x'
          includePreviewVersions: true
        displayName: Use .NET 5 
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '**/*.csproj'
        displayName: 'dotnet restore $(buildConfiguration)'
        
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--no-restore'
        displayName: 'dotnet build $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: True
          projects: '**/*.csproj'
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
        displayName: 'dotnet publish $(buildConfiguration)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'
        displayName: 'Upload artifacts'
    
- stage: Deploy
  displayName: Deploy 
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Azure Web App Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'Ansalemo(4388fa06-bf66-4497-82c2-991ba75ecb97)'
          appType: 'webAppLinux'
          WebAppName: 'aspnet-core-devops'
          ResourceGroupName: 'ansalemo-rg'
          packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
          
          