# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  vmImageName: ubuntu-latest
  environmentName: 'aspnet-core-devops'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
      - script: dotnet build --configuration $(buildConfiguration)
        displayName: 'dotnet build $(buildConfiguration)'

      - task: ArchiveFiles@2
        displayName: 'Archive Files'
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool: 
      vmImage: $(vmImageName)
      steps:
        - task: AzureRmWebAppDeployment@4
          displayName: 'Azure Web App Deploy'
          inputs:
            ConnectionType: 'AzureRM'
            azureSubscription: 'Ansalemo(4388fa06-bf66-4497-82c2-991ba75ecb97)'
            appType: 'webAppLinux'
            WebAppName: 'aspnet-core-devops'
            packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
            RuntimeStack: 'DOTNETCORE|5.0'
